name: pull-request
on:
  pull_request:
    branches: [ main ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node 
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Run tests 
        env:
          TEST_MONGODB_URI: ${{secrets.MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
        run: yarn test